apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
spec:
  rules:
    - host: chtitedev.FIXME.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: XX
                port:
                  number: YY